CREATE TABLE IF NOT EXISTS "clinics" (
	"id" serial PRIMARY KEY NOT NULL,
	"long_name_version" varchar(255) NOT NULL,
	"typeform_registration_link" varchar(255) NOT NULL,
	"pms" varchar(50) NOT NULL,
	"meta_title" varchar(255) NOT NULL,
	"meta_description" varchar(500) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"website" varchar(255) NOT NULL,
	"clinic_name" varchar(255) NOT NULL,
	"display_on_web" varchar(5) NOT NULL,
	"link_to_clinic_suburb_page" varchar(255) NOT NULL,
	"full_address" varchar(255) NOT NULL,
	"city" varchar(100) NOT NULL,
	"suburb" varchar(100) NOT NULL,
	"state" varchar(50) NOT NULL,
	"postcode" varchar(10) NOT NULL,
	"email" varchar(100) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"nearby1_txt" varchar(100) NOT NULL,
	"nearby1_link" varchar(255) NOT NULL,
	"nearby2_txt" varchar(100) NOT NULL,
	"nearby2_link" varchar(255) NOT NULL,
	"nearby3_txt" varchar(100) NOT NULL,
	"nearby3_link" varchar(255) NOT NULL,
	"nearby4_txt" varchar(100) NOT NULL,
	"nearby4_link" varchar(255) NOT NULL,
	"about_clinic" varchar(500) NOT NULL
);
