import { pgTable, serial, varchar, text, timestamp } from 'drizzle-orm/pg-core'

export const clinicsSchema = pgTable('clinics', {
  id: serial('id').primaryKey(),
  'Long Name Version': varchar('long_name_version').notNull(),
  'Typeform registration link': text('typeform_registration_link').notNull(),
  PMS: varchar('pms').notNull(),
  'Meta-title': text('meta_title').notNull(),
  'Meta-description': text('meta_description').notNull(),
  slug: varchar('slug').notNull(),
  Website: varchar('website').notNull(),
  'Clinic Name': varchar('clinic_name').notNull(),
  Display_on_web: varchar('display_on_web').notNull(),
  'link to clinic suburb page': varchar('link_to_clinic_suburb_page').notNull(),
  'Full Address': text('full_address').notNull(),
  City: varchar('city').notNull(),
  Suburb: varchar('suburb').notNull(),
  State: varchar('state').notNull(),
  Postcode: varchar('postcode').notNull(),
  Email: varchar('email').notNull(),
  Phone: varchar('phone').notNull(),
  nearby1_txt: varchar('nearby1_txt').notNull(),
  nearby1_link: varchar('nearby1_link').notNull(),
  nearby2_txt: varchar('nearby2_txt').notNull(),
  nearby2_link: varchar('nearby2_link').notNull(),
  nearby3_txt: varchar('nearby3_txt').notNull(),
  nearby3_link: varchar('nearby3_link').notNull(),
  nearby4_txt: varchar('nearby4_txt').notNull(),
  nearby4_link: varchar('nearby4_link').notNull(),
  'About Clinic': text('about_clinic').notNull(),
})
