import { pgTable, serial, varchar, timestamp } from 'drizzle-orm/pg-core'

export const clinicsSchema = pgTable('clinics', {
  id: serial('id').primaryKey(),
  'Long Name Version': varchar('long_name_version', { length: 255 }).notNull(),
  'Typeform registration link': varchar('typeform_registration_link', { length: 255 }).notNull(),
  PMS: varchar('pms', { length: 50 }).notNull(),
  'Meta-title': varchar('meta_title', { length: 255 }).notNull(),
  'Meta-description': varchar('meta_description', { length: 500 }).notNull(),
  slug: varchar('slug', { length: 100 }).notNull(),
  Website: varchar('website', { length: 255 }).notNull(),
  'Clinic Name': varchar('clinic_name', { length: 255 }).notNull(),
  Display_on_web: varchar('display_on_web', { length: 5 }).notNull(),
  'link to clinic suburb page': varchar('link_to_clinic_suburb_page', { length: 255 }).notNull(),
  'Full Address': varchar('full_address', { length: 255 }).notNull(),
  City: varchar('city', { length: 100 }).notNull(),
  Suburb: varchar('suburb', { length: 100 }).notNull(),
  State: varchar('state', { length: 50 }).notNull(),
  Postcode: varchar('postcode', { length: 10 }).notNull(),
  Email: varchar('email', { length: 100 }).notNull(),
  Phone: varchar('phone', { length: 20 }).notNull(),
  nearby1_txt: varchar('nearby1_txt', { length: 100 }).notNull(),
  nearby1_link: varchar('nearby1_link', { length: 255 }).notNull(),
  nearby2_txt: varchar('nearby2_txt', { length: 100 }).notNull(),
  nearby2_link: varchar('nearby2_link', { length: 255 }).notNull(),
  nearby3_txt: varchar('nearby3_txt', { length: 100 }).notNull(),
  nearby3_link: varchar('nearby3_link', { length: 255 }).notNull(),
  nearby4_txt: varchar('nearby4_txt', { length: 100 }).notNull(),
  nearby4_link: varchar('nearby4_link', { length: 255 }).notNull(),
  'About Clinic': varchar('about_clinic', { length: 500 }).notNull(),
})
